### ISSUE TITLE
Slide in animation not working

### ISSUE THREAD

**Issue by ttiamus** [victos/ng-busy#2]
I am updating a project to use your module from devyumao's angular2-busy. Once I updated, I noticed that the slide in animation when the throbber appears is gone. I also couldn't see the effect in your demo. Is this intended? I couldn't see anything in the CSS file that changed between the two projects to lose the animation.

Thanks for updating the project, and thanks for the help.

**Comment by victos** [comment]
Hello @ttiamus ,
I've fix the issue in the 1.4.4 . 
Thanks for your report. Have a good day.
