### ISSUE TITLE
can support Boolean ?

### ISSUE THREAD

**Issue by chaiizii** [victos/ng-busy#4]
<div [ngBusy]="true"></div>

**Comment by victos** [comment]
I don't think so. And I think there's a same way to reach the same goal.
```javascript
# the code below just like "showBusy = true;"
subject:Subject<any> = new Subject();
subscription:Subscription = subject.subscribe(() => {});
# the code below just like "showBusy=false;"
subject.complete();
```
just a little bit complex , right?

**Comment by wstow** [comment]
Hoping you can help, I want to show a busy indicator during route changes but I can't get it working.  With the old control I just used a boolean.

Here is my code:

`export class AppComponent {
  subject:Subject<any> = new Subject();
  busy:Subscription// = this.subject.subscribe(() => {});
  //# the code below just like "showBusy=false;"
 // subject.complete();

 constructor(private router: Router) {
   router.events.subscribe((routerEvent: Event) => {
    this.checkRouterEvent(routerEvent);
  })
}
  
checkRouterEvent(routerEvent: Event): void {
  if (routerEvent instanceof NavigationStart) {
    console.log('start')
    this.busy = this.subject.subscribe(() => {});
  }

  if (routerEvent instanceof NavigationEnd ||
    routerEvent instanceof NavigationCancel ||
    routerEvent instanceof NavigationError) {
    this.subject.complete();

    console.log('end')
  }
}
}`
