### ISSUE TITLE
Does not work in ChangeDetectionStrategy.OnPush component

### ISSUE THREAD

**Issue by Sky4CE** [victos/ng-busy#5]
`onStopBusy` never emmited, backdrop doesn't close. Any suggestions?

**Comment by Sky4CE** [comment]
@victos , problem is in `minDuration` option. If `minDuration` have been set then `OnPush` strategy wont work. I have fixed this situation and added full support for `OnPush`, you even not required to call markForCheck from ancestor component. Feel free to [grab my fork changes](https://github.com/Sky4CE/angular2-busy/commit/bfd80d702561812b7a5df3bd9363b808d3573ba0), sorry no time for PR =(
Just want to support your efforts to maintaining and rewriting this great (actually the only best) spinner lib for angular!

**Comment by Sky4CE** [comment]
Hey @victos , [please confirm PR ](https://github.com/victos/ng-busy/pull/6) and please create new release on npm. Really need this changes!

**Comment by victos** [comment]
Hi, @Sky4CE I'v merge the PR and release the new version, thanks for your efforts, and sorry for the late response.

**Comment by Sky4CE** [comment]
Thanks!
