### ISSUE TITLE
Busy Indicator Doesn't Appear With Observable returned From Service

### ISSUE THREAD

**Issue by ghost** [victos/ng-busy#8]
Using ng-busy 1.4.3 and Angular 5.x. Using an Angular Service injected into Component that returns an Observable:

Inside the service:
` public doIt(): Observable<any> {
    return Observable.create(s => {
      setTimeout(() => {
          console.log("We are done")
          s.complete();
        },
        5000);
    });
  }`

In the component:
`this.busy = this.myService.doIt().subscribe();`

The indicator *does not* appear. 

However if I take all the code inside the service and move it inline to the component *it works fine!* So the issue appears to be related to getting the observable from a service.

**Comment by victos** [comment]
Hi, @kingbd 
Could you please provide a online demo at https://stackblitz.com like [this](https://stackblitz.com/edit/angular-wxo3gx?file=src%2Fapp%2Fcomponents%2Fng-busy-test%2Fng-busy-test.component.ts)

**Comment by ghost** [comment]
Hi I created a stackblitz with dependencies at my version of Angular/ng-busy/rxjs

https://stackblitz.com/edit/angular-5uuf4t

Strange, on stackblitz it won't work as a Subscription, only a promise. Any ideas?

**Comment by victos** [comment]
Hi, @kingbd 
It works well when I upgrade rxjs from 5.5.6 to 5.5.11, can you upgrade the rxjs version and try again ?

**Comment by ghost** [comment]
Hi victos, upgrading to 5.5.11 indeed fixed the Subscription issue on stackblitz. And as you can see here:
https://stackblitz.com/edit/angular-3baiw2
I added a service that returns an observable and it works fine on stackblitz but even with rxjs 5.5.11 I still experience the original problem in my dev environment where the busy indicator is not working when observable is returned from service, only works when observable is inline. All my Angular versions/rxjs are the same as stackblitz so very frustrating problem. I have additional dependencies not included in the stackblitz, here is my whole package.json below. I don't know what else I can try to do to isolate the issue. thank you.

"dependencies": {
    "@angular/animations": "^5.2.10",
    "@angular/cdk": "^5.2.5",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/flex-layout": "^5.0.0-beta.14",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/material": "^5.2.5",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "@progress/kendo-angular-buttons": "^4.1.0",
    "@progress/kendo-angular-dateinputs": "^2.2.0",
    "@progress/kendo-angular-dialog": "^3.6.0",
    "@progress/kendo-angular-dropdowns": "^2.1.0",
    "@progress/kendo-angular-excel-export": "^1.0.7",
    "@progress/kendo-angular-grid": "^3.0.0",
    "@progress/kendo-angular-inputs": "^2.2.0",
    "@progress/kendo-angular-intl": "^1.4.0",
    "@progress/kendo-angular-l10n": "^1.2.0",
    "@progress/kendo-angular-layout": "^2.2.1",
    "@progress/kendo-data-query": "^1.2.2",
    "@progress/kendo-drawing": "^1.5.2",
    "@progress/kendo-theme-default": "^2.50.0",
    "circos": "^2.1.0",
    "core-js": "^2.4.1",
    "d3": "^4.5.0",
    "d3-queue": "^3.0.3",
    "d3-selection": "^1.3.0",
    "d3-tip": "^0.9.0",
    "ng-busy": "^1.4.8",
    "ngx-logger": "^2.2.4",
    "rxjs": "^5.5.11",
    "zone.js": "^0.8.19"
  }

**Comment by ghost** [comment]
Hi victos I believe I found the issue. In my service I was importing Observable from "rxjs" instead of "rxjs/Observable", now it behaves as expected. I appreciate you taking the time to look. Thank you
