### ISSUE TITLE
Angular 6 Update for RxJS 6 not in compatibility mode

### ISSUE THREAD

**Issue by mtpultz** [victos/ng-busy#9]
Looks like the NgBusy needs an update for Angular 6 to allow for use with RxJS v6 outside of compatibility mode.  Might be worth a version bump to v2.0?  Only needs to replace the imports using `rxjs/Subscription` a handful of times to be just `rxjs`.  

I'd PR an update, but not sure what needs to change in `build.js` globals and external.

**Comment by victos** [comment]
Hi, 
There's a 6.x version used for angular 6.x (rxjs v6)

**Comment by mtpultz** [comment]
Hi @victos, sorry I can only see master (v1.4.8) and v1.4.6 in the repo, and when I pull in master I get v1.4.8 that has dependencies that use version Angular v5.

**Comment by victos** [comment]
The code is in another project [here](https://github.com/victos/angular-opensource)

**Comment by mtpultz** [comment]
Thanks @victos!
